name: btl
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  flutter_launcher_icons: ^0.13.1
  flutter_staggered_animations: ^1.1.1
  flutterfire_cli: ^1.2.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  http: ^1.2.0
  emailjs: ^4.0.0
  uuid: ^4.4.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.4.2
  flutter_tts: ^4.0.2
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  sqflite: ^2.0.2+3
  path_provider: ^2.0.11
  quiver: ^3.2.2
  cupertino_icons: ^1.0.8

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/GridView.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/
    - lib/images/rate_icons/
    - assets/image/
